import { type BlogPost, BLOG_AUTHOR } from '../blog-types';

export const post: BlogPost = {
  slug: 'phoenix-kessaku-sky-bungalows-rajajinagar',
  propertySlug: 'phoenix-kessaku',
  title: 'Phoenix Kessaku: Sky Bungalows with 360° Views in Rajajinagar',
  metaTitle: 'Phoenix Kessaku, Rajajinagar — Price, Plans & Review',
  metaDescription:
    'Phoenix Kessaku offers one sky bungalow per floor with 360° views in Rajajinagar, West Bangalore, beside Orion Mall. Explore configurations, indicative pricing, the Callison clubhouse and connectivity.',
  excerpt:
    'Inside West Bangalore’s benchmark sky-bungalow address — one lavish residence per floor with 360-degree views in Rajajinagar, wrapped in a 50,000 sq ft Callison-designed clubhouse.',
  primaryKeyword: 'Phoenix Kessaku',
  keywords: [
    'Phoenix Kessaku', 'Phoenix Kessaku price', 'Phoenix Kessaku Rajajinagar',
    'sky bungalow Rajajinagar', 'luxury apartments Rajajinagar', 'ultra-luxury apartments West Bangalore',
    'Phoenix Kessaku floor plan', 'Phoenix Kessaku amenities', 'apartments near Orion Mall',
    'one apartment per floor Bangalore',
  ],
  datePublished: '2026-06-29',
  dateModified: '2026-06-29',
  readMinutes: 8,
  heroImage: '/images/phoenix-kessaku/0.png',
  heroAlt: 'Phoenix Kessaku sky bungalow towers with 360-degree city views in Rajajinagar, West Bangalore',
  category: 'Project Spotlight',
  body: [
    { t: 'p', html: 'Rising over Rajajinagar opposite Orion Mall, <strong>Phoenix Kessaku</strong> is among West Bangalore’s most exclusive ultra-luxury addresses — a cluster of soaring towers with just one lavish sky bungalow per floor. Developed by the Phoenix Group and named for a Japanese philosophy of grace, Kessaku pairs single-residence-per-floor privacy with sweeping 360-degree views of the cityscape. For buyers searching for the rarest sky-bungalow living in West Bangalore, it sets the benchmark.' },
    { t: 'p', html: 'This guide covers everything that matters before an enquiry: the configurations and indicative pricing, the landmark 50,000 sq ft Callison-designed clubhouse, the amenities and concierge lifestyle, the location and connectivity advantages of Rajajinagar, and why this corridor continues to attract HNI and NRI buyers seeking privacy without leaving the city.' },
    { t: 'h2', text: 'An Overview of Phoenix Kessaku' },
    { t: 'p', html: 'Developed by the Phoenix Group, Phoenix Kessaku is spread across roughly 4.5 acres on Dr. Rajkumar Road in Rajajinagar, opposite Orion Mall and the Brigade Gateway precinct. The community comprises around 108 uber-luxury 4 and 5 BHK residences and penthouses, with towers climbing up to 38 floors — making it one of West Bangalore’s tallest and most exclusive residential clusters.' },
    { t: 'p', html: 'Its defining idea is the <strong>sky bungalow</strong>: just one residence occupies each floor, so every home enjoys absolute privacy and uninterrupted 360-degree views across the city. Interiors are bespoke and finished to an exacting standard, with concierge living woven through. You can view the full specification on the <a href="/phoenix-kessaku">Phoenix Kessaku residence page</a>.' },
    { t: 'p', html: 'Anchoring community life is a 50,000 sq ft clubhouse designed by the renowned firm Callison, offering a sky lounge, swimming pool, squash court, mini-theatre, jacuzzi and curated wellness zones. Now ready to move, Kessaku is a completed, lived-in address rather than a project on paper — buyers purchase into a proven landmark with its clubhouse and services already running at full tilt.' },
    { t: 'h2', text: 'Location & Connectivity — Rajajinagar, West Bangalore' },
    { t: 'p', html: 'Rajajinagar is one of West Bangalore’s most established and premium neighbourhoods, and Phoenix Kessaku sits at its heart on Dr. Rajkumar Road, directly opposite <strong>Orion Mall and the Brigade Gateway precinct</strong>. That places premium retail, dining, multiplexes and a leading hospital within minutes, while the wider city remains easily reachable.' },
    { t: 'p', html: 'Connectivity is a particular strength: the Namma Metro on the Purple Line runs through Rajajinagar, with the Sandal Soap Factory station a short drive away, linking the address smoothly to the CBD, Whitefield and beyond. For a buyer, it is the rare combination of a settled, high-prestige locale with city-grade transit on the doorstep.' },
    { t: 'ul', items: [
      'Orion Mall / Brigade Gateway — adjacent',
      'Sandal Soap Factory Metro — approx. 5 minutes',
      'Manipal Hospital — approx. 10 minutes',
      'Kempegowda International Airport — approx. 45–60 minutes',
    ] },
    { t: 'h3', text: 'The Rajajinagar Growth Story' },
    { t: 'p', html: 'Rajajinagar, alongside Malleswaram, ranks among Bangalore’s most expensive and most stable micro-markets — a function of established infrastructure, mature social fabric and limited room for new supply. The arrival of the Purple Line metro has only sharpened that appeal: localities along operational metro corridors have seen property values rise materially, with sellers timing exits after metro operations reporting premiums of 15–20%.' },
    { t: 'p', html: 'For a buyer, the relevance is that Rajajinagar’s value is anchored to permanent infrastructure and prestige rather than a single market cycle. High-end West Bangalore addresses are prized for prestige, stability and strong rental returns — qualities that underpin long-term demand for a scarce ultra-luxury product like Kessaku.' },
    { t: 'h2', text: 'Configurations, Sizes & Indicative Pricing' },
    { t: 'p', html: 'Phoenix Kessaku offers expansive 4 and 5 BHK sky bungalows and penthouses, each occupying a full floor. Built-up areas span roughly 4,500 sq ft to over 8,000 sq ft, with the larger floor plans accommodating generous living and dining zones, wide decks and panoramic city frames.' },
    { t: 'ul', items: [
      '4 BHK Sky Bungalow — full-floor residence',
      '5 BHK Sky Bungalow — larger full-floor residence',
      'Penthouse — approx. up to 8,000+ sq ft',
    ] },
    { t: 'p', html: 'Indicative guide prices sit in the region of <strong>₹4.5 – 14 Cr</strong>, moving with configuration, floor level and view. As this is a scarce, invitation-led address, current availability and pricing are shared on enquiry; <a href="/phoenix-kessaku">request a private viewing here</a>.' },
    { t: 'p', html: 'For context, Rajajinagar is one of West Bangalore’s priciest micro-markets, and ultra-luxury, full-floor product commands a clear premium per square foot over standard apartments in the area. At Kessaku, that premium reflects three things: the single-residence-per-floor format, the 360-degree views from towers up to 38 floors, and the simple scarcity of sky-bungalow inventory anywhere in the city.' },
    { t: 'h2', text: 'Amenities & Lifestyle' },
    { t: 'p', html: 'Beyond the homes themselves, Kessaku is built around its landmark 50,000 sq ft Callison-designed clubhouse, which brings leisure, wellness and entertainment together under one roof and gives the address a resort-grade lifestyle within the city.' },
    { t: 'ul', items: [
      '50,000 sq ft Callison-designed clubhouse',
      'Swimming pool and sky lounge',
      'Mini theatre and banquet hall',
      'Squash court, gymnasium and jacuzzi',
      'Yoga and aerobics zone',
      'Concierge services and 24/7 gated security',
    ] },
    { t: 'h2', text: 'Why Phoenix Kessaku Is a Standout Investment' },
    { t: 'p', html: 'The investment case rests on scarcity and prestige. Sky-bungalow inventory — one residence per floor, with 360-degree views — is exceptionally rare in Bangalore, and Rajajinagar’s established, metro-connected micro-market supports stable, long-term value. A completed, Phoenix-built landmark carries lower execution risk than a new launch and appeals strongly to HNI and NRI buyers seeking a turnkey home of genuine distinction.' },
    { t: 'p', html: 'It is equally a lifestyle asset: a full-floor residence where panoramic city views, a world-class clubhouse and the retail and dining of Orion Mall are part of daily life. As always, value depends on the specific floor, configuration and timing, but the combination of a proven developer, a scarce format and a prestige corridor is an unusually durable one.' },
    { t: 'h2', text: 'Living at Phoenix Kessaku' },
    { t: 'p', html: 'Day-to-day life here is shaped by privacy and outlook. The private lift opens onto an entire floor, with wide decks and panoramic windows framing the city in every direction. Mornings might begin in the pool or yoga zone; afternoons move between the gymnasium, squash court and spa; evenings settle into the sky lounge, a film in the mini-theatre, or the restaurants and boutiques of Orion Mall a moment away.' },
    { t: 'p', html: 'For families and professionals, the appeal is the rare pairing of full-floor privacy with a five-star service infrastructure and a central West Bangalore address — metro on the doorstep, leading hospitals and schools nearby, and the wider city within easy reach beyond the gates.' },
    { t: 'h2', text: 'How Phoenix Kessaku Compares' },
    { t: 'p', html: 'Within the same Phoenix precinct in Rajajinagar, <a href="/phoenix-one-west">Phoenix One West</a> (One Bangalore West) offers integrated township living with 2.5, 3 and 4 BHK homes beside Orion Mall — a different balance of scale and price for buyers who do not need a full-floor format. Among the city’s other single-residence-per-floor landmarks, <a href="/prestige-kingfisher-towers">Prestige Kingfisher Towers</a> beside UB City is the closest CBD peer. Browse the full <a href="/#collection">collection of Bangalore residences</a> to compare side by side.' },
    { t: 'h2', text: 'Who Phoenix Kessaku Is For' },
    { t: 'p', html: 'Kessaku suits buyers who value privacy, views and prestige in equal measure — HNIs and NRIs seeking a landmark West Bangalore home, professionals who want metro connectivity at the door, and those drawn to the rarity of a sky bungalow. If you are weighing other options, you may also want to compare <a href="/phoenix-one-west">Phoenix One West</a> and <a href="/prestige-kingfisher-towers">Prestige Kingfisher Towers</a> from our collection, or explore the full <a href="/phoenix-kessaku">Phoenix Kessaku</a> specification before an enquiry.' },
    { t: 'h2', text: 'Frequently Asked Questions' },
  ],
  faqs: [
    { q: 'Where is Phoenix Kessaku located?', a: 'Phoenix Kessaku is on Dr. Rajkumar Road in Rajajinagar, West Bangalore, directly opposite Orion Mall and the Brigade Gateway precinct — about 5 minutes from Sandal Soap Factory Metro and 45–60 minutes from Kempegowda International Airport.' },
    { q: 'What is the price of apartments at Phoenix Kessaku?', a: 'Indicative guide prices sit in the region of ₹4.5 – 14 Cr, varying with configuration, floor level and view. As an invitation-led address, exact current pricing and availability are shared on enquiry.' },
    { q: 'What configurations are available at Phoenix Kessaku?', a: 'The development offers full-floor 4 and 5 BHK sky bungalows and penthouses, with built-up areas from roughly 4,500 sq ft to over 8,000 sq ft — just one residence per floor.' },
    { q: 'What amenities does Phoenix Kessaku offer?', a: 'Highlights include a 50,000 sq ft Callison-designed clubhouse with a sky lounge, swimming pool, squash court, mini-theatre, jacuzzi, gymnasium, yoga and aerobics zone, banquet hall, concierge services and 24/7 gated security.' },
    { q: 'Is Phoenix Kessaku a good investment?', a: 'Rajajinagar is an established, metro-connected and stable micro-market, and sky-bungalow inventory is exceptionally scarce, which supports long-term value. As always, value depends on the specific floor, configuration and timing.' },
  ],
  related: [],
  author: BLOG_AUTHOR,
};
