/** @type {import('next').NextConfig} */
const nextConfig = {
  // SSR-capable (no static export) — pages are statically generated by default
  // via generateStaticParams, but can become dynamic/ISR later without a rewrite.
  reactStrictMode: true,
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'images.unsplash.com' },
    ],
  },
};

export default nextConfig;
