/* ============================================================
   Perfect Neighbourhood — property dataset (single source).
   Facts researched from public listings (mid-2026). Indicative.
   ============================================================ */
/* Paste your Google Apps Script Web App URL between the quotes to send
   all enquiry forms into your Google Sheet. Leave empty for demo mode. */
export const SHEETS_URL = "https://script.google.com/macros/s/AKfycbwyjAltbO1_JVxopf4Cwmrpo8V8JFMNb9bcDQqNnyXR3oJsBlgqzEWx8erEw4eoaupT/exec";

export const PROPERTIES = [
{
  slug:"prestige-golfshire", name:"Prestige Golfshire", full:"Prestige Golfshire",
  loc:"Nandi Hills, Devanahalli", micro:"Foothills of Nandi Hills, off Nandi Hills Road, Devanahalli, North Bangalore",
  developer:"Prestige Group", type:"villa", status:"invite", facing:"North", verified:true,
  entry:"9", range:"₹9 – 20 Cr", sqft:"5,000–10,000", priceRange:"₹9 – 20+ Cr", sizeRange:"5,000 – 10,000+ sq ft",
  possession:"Ready to move", img:"1600596542815-ffad4c1539a9", lat:13.370, lng:77.683,
  hi:["15 min to Kempegowda Int'l Airport","At the foot of Nandi Hills, on a private lake"],
  tags:["Hills-facing","Lakefront","Golf"],
  configs:["3 BHK Villa · 5,000–7,000 sq ft","4 BHK Villa · 7,000–10,000 sq ft","5 BHK Villa · 10,000+ sq ft"],
  overview:"Prestige Golfshire is an ultra-luxury villa estate sprawled across roughly 275 acres at the verdant base of Nandi Hills in Devanahalli. Conceived around an 18-hole signature championship golf course, the gated enclave houses just over 200 bespoke villas, each commanding sweeping views of fairways, water bodies and the surrounding hills. Residences range from expansive 3 BHK homes to palatial 5 BHK mansions exceeding 10,000 sq ft, finished to exacting standards. Anchoring community life is The Falcon Greens clubhouse, complemented by a luxury resort, fine-dining, spa, pool and racquet courts. Minutes from Kempegowda International Airport via NH-44, Golfshire blends serene countryside living with effortless connectivity to the airport and the Aerospace SEZ.",
  amenities:["18-hole championship golf course","The Falcon Greens clubhouse","Luxury resort & fine-dining","Spa and wellness centre","Swimming pools","Squash and tennis courts","Golf academy & pro shop","Landscaped gardens & water features","24/7 gated security"],
  connectivity:[{place:"Kempegowda International Airport",minutes:"15–25 min"},{place:"Nandi Hills",minutes:"20–30 min"},{place:"Devanahalli Business Park / Aerospace SEZ",minutes:"15–25 min"},{place:"Manyata Tech Park",minutes:"45–60 min"}],
  usp:["18-hole championship golf course with golf-facing villas","Scenic foothills-of-Nandi-Hills setting on ~275 acres","Integrated luxury resort and Falcon Greens clubhouse lifestyle"],
  sources:["https://www.prestigengroup.com/projects-in-bangalore/prestige-golfshire/"]
},
{
  slug:"embassy-boulevard", name:"Embassy Boulevard", full:"Embassy Boulevard",
  loc:"Yelahanka, North Bangalore", micro:"Hosahalli Main Road, off International Airport Road, Yelahanka, North Bangalore",
  developer:"Embassy Group", type:"villa", status:"ready", facing:"East", verified:true,
  entry:"6", range:"₹6 – 16 Cr", sqft:"3,935–7,310", priceRange:"₹6 – 16+ Cr", sizeRange:"3,935 – 7,310 sq ft",
  possession:"Ready to move", img:"1613490493576-7fde63acd811", lat:13.101, lng:77.596,
  hi:["20 min to Kempegowda Int'l Airport","Gated villa community with a 100,000 sq ft clubhouse"],
  tags:["Private Pool","Private Lift","Clubhouse"],
  configs:["3 BHK Villa","4 BHK Villa","5 BHK Villa","Themes: Pine · Willow · Cedar · Silver Oak · Cypress"],
  overview:"Embassy Boulevard is an address of rarefied privacy — a gated community of 170 architect-designed villas set across 51 manicured acres off International Airport Road in North Bangalore. Each villa is themed across five distinctive typologies — Pine, Willow, Cedar, Silver Oak and Cypress — with built-up areas spanning 3,935 to 7,310 sq ft. Homes come appointed with private heated pools, personal elevators, landscaped gardens and outdoor barbecue terraces, delivering resort-like indulgence within one's own gates. At its heart sits a lavish 100,000 sq ft clubhouse offering curated recreation, wellness and dining. Its proximity to Kempegowda International Airport and the northern business corridors makes it a coveted choice for discerning executives seeking turnkey ultra-luxury.",
  amenities:["100,000 sq ft clubhouse","Private heated pool per villa","Private elevator per villa","Landscaped gardens","Outdoor barbecue terraces","Jogging & strolling tracks","Children's play areas","Indoor sports facilities","24/7 surveillance"],
  connectivity:[{place:"Kempegowda International Airport",minutes:"20–30 min"},{place:"Yelahanka",minutes:"10–15 min"},{place:"Manyata Tech Park",minutes:"30–40 min"},{place:"Hebbal",minutes:"25–35 min"}],
  usp:["Every villa features a private heated pool and private elevator","Five distinct architect-designed villa themes across 51 acres","Expansive 100,000 sq ft professionally managed clubhouse"],
  sources:["https://www.embassyboulevard.com/embassy-boulevard-villas-bangalore/"]
},
{
  slug:"embassy-lake-terraces", name:"Embassy Lake Terraces", full:"Embassy Lake Terraces",
  loc:"Hebbal, North Bangalore", micro:"Hebbal Kempapura, near Hebbal & Nagavara Lakes, off the Outer Ring Road",
  developer:"Embassy Group", type:"apartment", status:"ready", facing:"North-East", verified:true,
  entry:"7", range:"₹7 – 23 Cr", sqft:"3,536–7,809", priceRange:"₹7 – 23+ Cr", sizeRange:"3,536 – 7,809+ sq ft",
  possession:"Ready to move", img:"1545324418-cc1a3fa10c00", lat:13.041, lng:77.591,
  hi:["10 min to Manyata Tech Park","Overlooking Hebbal Lake from a 2-acre sky deck"],
  tags:["Lake View","Sky Deck","Private Lift"],
  configs:["3 BHK Apartment","4 BHK Apartment","4 BHK Duplex Penthouse · ~7,800 sq ft","5 BHK Penthouse · ~9,300 sq ft"],
  overview:"Embassy Lake Terraces redefines vertical luxury in North Bangalore, rising as nine sculpted towers across a landscaped 14.5-acre site in Hebbal. The development's 467 exclusive residences — from generous 3 and 4 BHK apartments to sprawling duplex penthouses — open onto panoramic vistas of Hebbal and Nagavara lakes. Interiors are uncompromising: private lifts opening into homes, centralised air-conditioning and Italian marble flooring as standard. Residents move through a six-acre landscaped courtyard and a dramatic two-acre elevated sky deck — amenities rarely matched at this scale in the city. Strategically located off the Outer Ring Road and minutes from Manyata Tech Park, it marries serene lakefront luxury with the connectivity demands of senior executives.",
  amenities:["2-acre elevated sky deck","6-acre landscaped courtyard","Private lift access to apartments","Centralised air-conditioning","Italian marble flooring","Swimming pool","Clubhouse with spa & gym","Panoramic lake views","24/7 security & concierge"],
  connectivity:[{place:"Manyata Tech Park",minutes:"10–15 min"},{place:"Hebbal flyover / ORR",minutes:"5–10 min"},{place:"Kempegowda International Airport",minutes:"30–40 min"},{place:"Bangalore CBD (MG Road)",minutes:"30–40 min"}],
  usp:["Unmatched 2-acre sky deck and 6-acre landscaped courtyard","Panoramic lake views with private-lift residences","Ultra-luxury duplex penthouses exceeding 9,000 sq ft"],
  sources:["https://www.99acres.com/embassy-lake-terraces-hebbal-kempapura-bangalore-north-npxid-r8574"]
},
{
  slug:"embassy-springs-the-grove", name:"Embassy Springs — The Grove", full:"Embassy Springs — The Grove",
  loc:"Devanahalli, North Bangalore", micro:"The Grove precinct, Embassy Springs township, Sadahalli, off Airport Road (NH-44)",
  developer:"Embassy Group", type:"plot", status:"ready", facing:"East", verified:true,
  entry:"1.94", range:"₹1.94 – 8 Cr", sqft:"2,100–13,000", priceRange:"₹1.94 – 8+ Cr", sizeRange:"2,100 – 13,000 sq ft (plots)",
  possession:"Plotted — phased handover", img:"", lat:13.249, lng:77.711,
  hi:["10 min to International Airport","Plots within a 288-acre integrated township"],
  tags:["Plotted","Greenway","Township"],
  configs:["Villa plots · 2,100–13,000 sq ft","Corner plots","East-facing plots","Built-to-suit villas"],
  overview:"The Grove is a premium villa-plot precinct within Embassy Springs — the Group's flagship integrated township spread across nearly 288 acres at Sadahalli on Devanahalli's Airport Road. Designed for those who wish to craft a bespoke home, The Grove offers fully serviced villa plots ranging from 2,100 to around 13,000 sq ft, including coveted corner and east-facing configurations, within a secure, master-planned community. The township envelops residents in over 45 acres of greenery, a 5.5-acre man-made lake and more than 30 themed parks, underpinned by solar street lighting, rainwater harvesting and recycled-water irrigation. Anchored by international schools, a business park and a sports arena, it is a self-contained luxury ecosystem barely ten kilometres from the airport.",
  amenities:["5.5-acre man-made lake","45+ acres of greenery","32+ themed parks","Grand clubhouse & sports arena","Swimming pools","International schools on-site","Solar street lighting","Rainwater harvesting","24/7 gated security"],
  connectivity:[{place:"Kempegowda International Airport",minutes:"10–15 min"},{place:"NH-44 / Sadahalli Gate",minutes:"2–5 min"},{place:"KIADB Aerospace SEZ",minutes:"15–20 min"},{place:"Stonehill International School",minutes:"15–20 min"}],
  usp:["Customisable serviced villa plots within a 288+ acre township","Sustainability-led infrastructure throughout","Just ~10 km from Kempegowda International Airport"],
  sources:["https://embassysprings.org/"]
},
{
  slug:"godrej-reserve", name:"Godrej Reserve", full:"Godrej Reserve",
  loc:"Devanahalli, North Bangalore", micro:"Devanahalli, off Airport Road (NH-44), North Bangalore",
  developer:"Godrej Properties", type:"plot", status:"ready", facing:"North", verified:true,
  entry:"0.74", range:"₹0.74 – 2 Cr", sqft:"1,200–3,200", priceRange:"₹0.74 – 2+ Cr", sizeRange:"1,200 – 3,200 sq ft (plots)",
  possession:"Under development · possession from 2030", img:"1505691938895-1758d7feb511", lat:13.231, lng:77.706,
  hi:["15 min to International Airport","Forest-themed plots bordering a reserved forest"],
  tags:["Forest Edge","Plotted","Gated"],
  configs:["30x40 · 1,200 sq ft","30x50 · 1,500 sq ft","30x60 · 1,800 sq ft","40x60 · 2,400 sq ft","40x80 · 3,200 sq ft"],
  overview:"Godrej Reserve is a forest-themed plotted enclave by Godrej Properties, set across roughly 95.7 acres in Devanahalli — the rapidly emerging luxury corridor near Kempegowda International Airport. Conceived around a 'reserve' philosophy of curated greenery and open landscape, the RERA-approved community offers around 950 villa plots in dimensions from 30x40 up to expansive 40x80 parcels, empowering buyers to build bespoke homes at their own pace. Residents enjoy a clubhouse, swimming pool, gymnasium, indoor games, outdoor sports courts and a dedicated party area, alongside landscaped gardens and children's play zones. With prices opening from approximately ₹74 lakh, Godrej Reserve combines the credibility of a trusted developer with the appreciation potential of Devanahalli's airport-led growth.",
  amenities:["Clubhouse","Swimming pool","Gymnasium","Outdoor sports courts","Indoor games","Party / banquet area","Landscaped gardens","Children's play area","Forest-themed greens","24/7 gated security"],
  connectivity:[{place:"Kempegowda International Airport",minutes:"15–25 min"},{place:"NH-44 / Airport Road",minutes:"5–10 min"},{place:"Devanahalli town",minutes:"10–15 min"},{place:"Aerospace SEZ / Business Park",minutes:"15–25 min"}],
  usp:["Forest-themed, low-density plotted living by Godrej Properties","Wide choice of plot dimensions for custom homes","Strong appreciation potential in the airport-led corridor"],
  sources:["https://www.squareyards.com/bangalore-residential-property/godrej-reserve/10309/project"]
},
{
  slug:"prestige-dew-drops", name:"Prestige Dew Drops", full:"Prestige Dew Drops",
  loc:"Rajanukunte, North Bangalore", micro:"Doddaballapura Main Road, Rajanukunte / Sreeramanahalli, North Bangalore",
  developer:"Prestige Group", type:"villa", status:"ready", facing:"West", verified:true,
  entry:"6.99", range:"₹6.99 – 11.69 Cr", sqft:"3,508–5,868", priceRange:"₹6.99 – 11.69 Cr", sizeRange:"3,508 – 5,868 sq ft",
  possession:"Possession from 2026", img:"1564013799919-ab600027ffc6", lat:13.163, lng:77.553,
  hi:["A low-density enclave of only 25 villas","75% of the land kept as open green space"],
  tags:["Low Density","Private Garden","Gated"],
  configs:["3 BHK Villa","4 BHK Villa · up to 5,868 sq ft"],
  overview:"Prestige Dew Drops is an intimate gated enclave of just 25 ultra-luxury villas set across 5.4 verdant acres along Doddaballapura Main Road in serene North Bangalore. Crafted by the Prestige Group, the community arranges its 3 and 4 BHK residences in five elegant rows, with sweeping 3,508 to 5,868 sq ft layouts that prioritise light, privacy and feng-shui-aligned planning. An expansive 75% of the land is dedicated to open green space, complemented by over thirty curated amenities including a clubhouse, mini theatre and dedicated zones for children and seniors. Positioned away from the city's bustle yet within convenient reach of the airport and Yelahanka, the enclave offers a tranquil, low-density lifestyle increasingly rare near Bengaluru.",
  amenities:["Clubhouse","Swimming pool","Gymnasium","Mini theatre","Senior citizens' park","Children's play area","Skating rink","Landscaped gardens (75% open)","Jogging tracks","24/7 security"],
  connectivity:[{place:"Kempegowda International Airport",minutes:"30–40 min"},{place:"Yelahanka",minutes:"~25 min"},{place:"Yelahanka Railway Station",minutes:"~20 min"},{place:"Doddaballapura town",minutes:"~20 min"}],
  usp:["Ultra-exclusive enclave of only 25 villas across 5.4 acres","75% open green space with 30+ amenities","Feng-shui-aligned layouts in a peaceful North Bangalore setting"],
  sources:["https://www.prestigespringheights.info/prestige-group/prestige-dew-drops.html"]
},
{
  slug:"brigade-orchards-signature", name:"Brigade Orchards — Signature", full:"Brigade Orchards — Signature Villas",
  loc:"Devanahalli, North Bangalore", micro:"Brigade Orchards township, off Boodigere Road / NH-207, Devanahalli",
  developer:"Brigade Group", type:"villa", status:"invite", facing:"North-East", verified:true,
  entry:"4.51", range:"₹4.5 – 6 Cr", sqft:"4,900–4,920", priceRange:"₹4.51 – 4.57 Cr", sizeRange:"4,900 – 4,920 sq ft",
  possession:"Ready to move · OC received", img:"1568605114967-8130f3a36994", lat:13.227, lng:77.717,
  hi:["10–20 min to International Airport","Villas designed around mature existing trees"],
  tags:["Smart Township","Tree-centric","Sports"],
  configs:["4 BHK Villa · Chrysanthemum","4 BHK Villa · Tulip","4 BHK Villa · Carnation"],
  overview:"Brigade Orchards Signature Villas form the premium villa address within Brigade Group's award-winning 135-acre integrated smart township in Devanahalli. These ready-to-move 4 BHK homes — offered in three distinctive designs — span a generous 4,900-plus sq ft and are conceived around mature trees rather than rigid floor plans, recreating old Bangalore's charm of large bungalows amid abundant greenery. Residents enjoy resort-grade township infrastructure, including the five-star Signature Club Resort, a cricket and football sports arena, a CBSE school, a proposed medical centre and a commercial complex — all within a self-sufficient, walkable community. Set minutes from the airport and the KIADB Aerospace Park, the villas combine privacy, panoramic green vistas and effortless connectivity.",
  amenities:["Five-star Signature Club Resort","Cricket & football arena","Swimming pool","Gymnasium","CBSE school on-site","Proposed medical centre","Retail & commercial complex","Tree-centric landscaping","24/7 security"],
  connectivity:[{place:"Kempegowda International Airport",minutes:"10–20 min"},{place:"NH-44 (Bellary Road)",minutes:"~8 min"},{place:"KIADB Aerospace Park",minutes:"Adjacent"},{place:"Devanahalli town",minutes:"15–20 min"}],
  usp:["Inside a self-sufficient 135-acre smart township","Ready villas designed around existing trees","10–20 minutes from the international airport"],
  sources:["https://www.brigadeorchards.com/residences/signature-villas"]
},
{
  slug:"bhartiya-city-leela", name:"Bhartiya City — Leela", full:"Bhartiya City — Leela Residences",
  loc:"Thanisandra, North Bangalore", micro:"Thanisandra Main Road, within Bhartiya City township, near Hebbal & Manyata",
  developer:"Bhartiya Urban", type:"apartment", status:"ready", facing:"East", verified:true,
  entry:"1.5", range:"₹1.5 – 5.26 Cr", sqft:"846–4,209", priceRange:"₹1.5 – 5.26 Cr", sizeRange:"846 – 4,209 sq ft",
  possession:"Ready · delivered from 2020", img:"", lat:13.063, lng:77.625,
  hi:["15 min to Manyata Tech Park","Leela-serviced residences in a city-within-a-city"],
  tags:["Leela Serviced","Township","Sky Deck"],
  configs:["Studio Apartment","1 & 2 BHK","3 BHK","4 BHK · up to 4,209 sq ft"],
  overview:"Leela Residences at Bhartiya City is among India's first hotel-branded residences, blending the legendary hospitality of The Leela with refined urban living on Thanisandra Main Road in North Bengaluru. Set within the landmark Bhartiya City township, these 176 homes rise across elegant towers and span studios to expansive 4 BHK layouts of 846 to 4,209 sq ft, each backed by Leela-style concierge and signature spa services. Residents enjoy resort-grade amenities, an adjoining five-star Leela hotel, lush landscaped greens, fine dining and a self-contained ecosystem that includes a 3.7-million-sq-ft SEZ office hub, retail boulevard and school. Strategically placed near Manyata Tech Park, Hebbal and the Outer Ring Road, it offers seamless live-work-play convenience.",
  amenities:["Leela Spa & sauna","Swimming pool","Gymnasium","Clubhouse with lounge & bar","Mini theatre","Jogging track","Landscaped gardens","Retail & fine dining on-site","Adjoining five-star Leela hotel"],
  connectivity:[{place:"Manyata Tech Park",minutes:"~15 min"},{place:"Kempegowda International Airport",minutes:"30–35 min"},{place:"Hebbal / ORR",minutes:"15–20 min"},{place:"Thanisandra Main Road",minutes:"Adjacent"}],
  usp:["Among India's first Leela hotel-branded residences","Inside an integrated township with SEZ, retail and school","Close to Manyata Tech Park with strong rental demand"],
  sources:["https://www.homznspace.com/leela-residences-bhartiya-city/"]
},
{
  slug:"prestige-white-meadows", name:"Prestige White Meadows", full:"Prestige White Meadows",
  loc:"Whitefield, East Bangalore", micro:"Whitefield Main Road near Hope Farm Junction / ECC Road, adjacent to ITPL",
  developer:"Prestige Group", type:"villa", status:"invite", facing:"North", verified:true,
  entry:"6.9", range:"₹6.9 – 25 Cr", sqft:"4,111–12,000", priceRange:"₹6.9 – 25+ Cr", sizeRange:"4,111 – 12,000+ sq ft",
  possession:"Ready to move", img:"1600585154340-be6161a56a0c", lat:12.958, lng:77.726,
  hi:["ITPL tech parks at the doorstep","Stepped-terrace villas & triplex bungalows"],
  tags:["Sky Villas","Triplex Bungalows","Gated"],
  configs:["4 BHK Sky Villa","5 BHK Triplex Independent Bungalow · up to 12,000+ sq ft"],
  overview:"Prestige White Meadows is one of Whitefield's most prestigious luxury enclaves, set across roughly 28.5 acres along Whitefield Main Road near Hope Farm Junction and ITPL. This rare mixed-format community pairs 288 high-rise 4 BHK Sky Villas — housed in elegant G+27 towers — with around 61 sprawling 5 BHK triplex independent bungalows, offering homes from 4,111 sq ft to over 12,000 sq ft. Distinctive stepped-terrace architecture follows the site's gentle acclivity, while interiors feature imported marble, teak woodwork and engineered flooring. Residents enjoy a comprehensive amenity suite including a clubhouse, pool, tennis and squash courts, gymnasium and landscaped gardens. Positioned at the heart of Bengaluru's eastern tech corridor, White Meadows delivers ready, ultra-premium living where land scarcity has driven strong appreciation.",
  amenities:["Clubhouse","Swimming pool","Gymnasium / health club","Tennis & squash courts","Badminton courts","Billiards & snooker","Amphitheatre & gardens","Children's pool & play area","Coffee shop & retail"],
  connectivity:[{place:"ITPL / Whitefield tech parks",minutes:"~5 min"},{place:"MG Road / city centre",minutes:"25–30 min"},{place:"Kempegowda International Airport",minutes:"30–40 min"},{place:"Whitefield Metro (Purple Line)",minutes:"5–10 min"}],
  usp:["Rare mix of 4 BHK sky villas and 5 BHK triplex bungalows","Stepped-terrace architecture with imported finishes","Prime ready Whitefield address beside ITPL"],
  sources:["https://www.99acres.com/prestige-white-meadows-whitefield-bangalore-east-npxid-r768"]
},
{
  slug:"total-environment-rhapsody", name:"Total Environment — Rhapsody", full:"Total Environment — Pursuit of a Radical Rhapsody",
  loc:"Whitefield, East Bangalore", micro:"ITPL Main Road, Whitefield (Hoodi growth belt), Bengaluru",
  developer:"Total Environment", type:"villa", status:"ready", facing:"East", verified:true,
  entry:"3.49", range:"₹3.49 – 15.28 Cr", sqft:"2,753–8,023", priceRange:"₹3.49 – 15.28+ Cr", sizeRange:"2,753 – 8,023 sq ft",
  possession:"Under construction · phased", img:"", lat:12.989, lng:77.741,
  hi:["85% of the campus kept as open green","Customisable homes via the eDesign platform"],
  tags:["Biophilic","Earth-sheltered","Architect Series"],
  configs:["2 & 3 BHK Apartment","4 BHK Apartment","4 BHK Earth-Sheltered Villa","5 BHK Penthouse"],
  overview:"Pursuit of a Radical Rhapsody is Total Environment's signature biophilic masterpiece on ITPL Main Road, Whitefield, spread across roughly 37 acres with an extraordinary 85% open green space. The development reimagines urban luxury through nature-integrated design, offering 2, 3 and 4 BHK apartments, opulent 5 BHK penthouses and just 17 rare 4 BHK earth-sheltered villas, with saleable areas spanning 2,753 to over 8,000 sq ft. Hallmarks include handcrafted wire-cut brick facades, open-to-sky private gardens with every home, lake-facing decks and natural-insulation earth-sheltered rooftops. Total Environment's acclaimed eDesign platform lets buyers customise interiors to a degree unmatched in the market. With hospitals, malls and leading schools minutes away, Rhapsody offers a deeply crafted, sustainable luxury rarely found in Bengaluru.",
  amenities:["Heated swimming pool","Squash court","Music room","Reading area / library","Café","Art wall","Private open-to-sky gardens per home","Lake-facing decks","Landscaped greens (85% open)"],
  connectivity:[{place:"Manipal Hospital, Whitefield",minutes:"~3 min"},{place:"Forum Shantiniketan Mall",minutes:"~5 min"},{place:"MG Road / city centre",minutes:"30–40 min"},{place:"Kempegowda International Airport",minutes:"~60 min"}],
  usp:["Biophilic, customisable homes with private open-to-sky gardens","Rare earth-sheltered villas (only 17) on an 85%-green campus","Prime Whitefield location near hospitals, malls and schools"],
  sources:["https://www.total-environment.com/pursuit-of-a-radical-rhapsody"]
},
{
  slug:"embassy-grove", name:"Embassy Grove", full:"Embassy Grove",
  loc:"Kodihalli, Off Old Airport Rd", micro:"Rustum Bagh, Kodihalli, off Old Airport Road, near Indiranagar",
  developer:"Embassy Group", type:"villa", status:"sold", facing:"North-West", verified:true,
  entry:"11", range:"₹11 – 20 Cr", sqft:"4,337–6,346", priceRange:"₹11 – 20 Cr", sizeRange:"4,337 – 6,346 sq ft",
  possession:"Ready to move", img:"1600585154340-be6161a56a0c", lat:12.961, lng:77.648,
  hi:["Adjacent to the Karnataka Golf Association","5–10 min to MG Road & The Leela"],
  tags:["CBD Villaments","Private Pool","IGBC Platinum"],
  configs:["4 BHK Duplex Villament","5 BHK Triplex Villament · up to 6,346 sq ft"],
  overview:"Embassy Grove is an ultra-luxury enclave of just 106 duplex and triplex villaments set across roughly 8 acres in Rustum Bagh, Kodihalli — moments from Indiranagar and Old Airport Road. Conceived by the Embassy Group, it reinvents central-Bangalore living by blending the privacy of a villa with the convenience of an apartment. Each residence spans 4,300 to over 6,300 sq ft and arrives with its own private pool, sun deck and landscaped garden or terrace, central air-conditioning and a Nolte kitchen. The IGBC Platinum pre-certified community is zero-vehicle at ground level, freeing the podium for greenery, a clubhouse, spa, gym and concierge. Adjacent to the Karnataka Golf Association course and minutes from MG Road, it offers estate-style grandeur within the prime CBD.",
  amenities:["Private pool & sun deck per home","Clubhouse","Gymnasium","Spa & salon","Swimming pool","Yoga studio","Concierge services","Central air-conditioning","Nolte modular kitchen"],
  connectivity:[{place:"MG Road",minutes:"5–10 min"},{place:"The Leela / Galleria",minutes:"~2 min"},{place:"Karnataka Golf Association",minutes:"Adjacent"},{place:"Kempegowda International Airport",minutes:"45–60 min"}],
  usp:["Rare CBD villament living with a private pool per home","Ultra-low density of only 106 units across ~8 acres","IGBC Platinum, zero-vehicle ground level beside the KGA"],
  sources:["https://www.embassyprojectsindia.com/embassy-grove/"]
},
{
  slug:"adarsh-palm-retreat", name:"Adarsh Palm Retreat", full:"Adarsh Palm Retreat",
  loc:"Bellandur, East Bangalore", micro:"Devarabisanahalli, Bellandur, off ORR / Sarjapur Road, near RMZ Ecospace",
  developer:"Adarsh Developers", type:"villa", status:"ready", facing:"East", verified:true,
  entry:"2.2", range:"₹2.2 – 6 Cr", sqft:"2,230–4,805", priceRange:"₹2.2 – 6 Cr", sizeRange:"2,230 – 4,805 sq ft",
  possession:"Ready to move", img:"1512917774080-9991f1c4c750", lat:12.928, lng:77.681,
  hi:["5 min to RMZ Ecospace tech parks","250-acre township with a 65,000 sq ft clubhouse"],
  tags:["Lakeside","65k Clubhouse","Gated"],
  configs:["3 BHK Apartment","4 BHK Apartment","4 BHK Villa","4.5 BHK Villa"],
  overview:"Adarsh Palm Retreat is one of Bangalore's largest and most established gated townships, spread across roughly 250 acres in Bellandur, on the edge of the Outer Ring Road and Sarjapur Road IT corridor. The integrated community blends independent villas and premium apartments, ranging from around 2,230 to 4,805 sq ft, within a leafy, master-planned campus surrounded by Fortune 500 offices at RMZ Ecospace and Ecoworld. Residents enjoy an expansive clubhouse of over 65,000 sq ft, swimming pools, tennis courts, jogging tracks, landscaped gardens and meditation spaces. Its standout appeal is location: the township sits at the convergence of the ORR, Sarjapur Main Road and Koramangala Inner Ring Road, placing tech parks, international schools and Marathahalli within minutes.",
  amenities:["65,000+ sq ft clubhouse","Outdoor swimming pools","Tennis courts","Gymnasium","Jogging track","Meditation room","Party hall","Table tennis & billiards","24/7 gated security"],
  connectivity:[{place:"RMZ Ecospace / Ecoworld",minutes:"~5 min"},{place:"ORR (Marathahalli)",minutes:"5–10 min"},{place:"Sarjapur Road",minutes:"~10 min"},{place:"Kempegowda International Airport",minutes:"50–60 min"}],
  usp:["Vast ~250-acre township in the heart of the IT corridor","Among Bangalore's largest clubhouses at 65,000+ sq ft","Villas and apartments amid Fortune 500 campuses"],
  sources:["https://www.99acres.com/adarsh-palm-retreat-bellandur-bangalore-east-npxid-r15248"]
},
{
  slug:"nambiar-bellesa", name:"Nambiar Bellesa", full:"Nambiar Bellezea",
  loc:"Sarjapur Road, East Bangalore", micro:"Off Sarjapur Road, near Dommasandra, East Bangalore",
  developer:"Nambiar Builders", type:"villa", status:"ready", facing:"North-East", verified:true,
  entry:"3.65", range:"₹3.65 – 16 Cr", sqft:"3,100–3,900", priceRange:"₹3.65 – 16 Cr", sizeRange:"3,100 – 3,900 sq ft (villas)",
  possession:"Ready · newer phases to 2026", img:"", lat:12.882, lng:77.741,
  hi:["15–20 min to Sarjapur IT hubs","Resort-style 70-acre villa township"],
  tags:["Resort Style","Floodlit Tennis","Bespoke"],
  configs:["4 BHK Villa","5 BHK Villa","Residential Plots · 1,200–2,400 sq ft"],
  overview:"Nambiar Bellezea is a sprawling luxury villa community by Nambiar Builders, set across roughly 70 acres off Sarjapur Road in east Bangalore. Conceived as a resort-style oasis, it pairs bespoke 4 and 5 BHK villas — typically 3,100 to 3,900 sq ft — with custom plots that let buyers shape their own homes amid abundant landscaping. More than a decade in the making, the gated township is celebrated for its sporting and lifestyle infrastructure: floodlit tennis courts, a futsal field with artificial turf, basketball and volleyball courts, a Parisian-style cafe, clubhouse, swimming pool and round-the-clock security. Positioned on the fast-growing Sarjapur corridor, with proximity to leading IT parks and international schools, Bellezea offers an enviable balance of green, low-density living and connectivity.",
  amenities:["Clubhouse","Swimming pool","Two floodlit tennis courts","Futsal field (artificial turf)","Basketball & volleyball courts","Parisian-style café","Gymnasium","Private villa gardens","24/7 gated security"],
  connectivity:[{place:"Sarjapur Road",minutes:"5–10 min"},{place:"Wipro / Sarjapur IT hubs",minutes:"15–20 min"},{place:"ORR (Marathahalli)",minutes:"25–30 min"},{place:"Electronic City",minutes:"30–40 min"}],
  usp:["Resort-style ~70-acre township with customisable floor plans","Exceptional sporting amenities incl. floodlit tennis & futsal","Established, RERA-registered, sustainably built"],
  sources:["https://nambiarbuilders.com/bellezea/"]
},
{
  slug:"tata-promont", name:"Tata Promont", full:"Tata Promont",
  loc:"Banashankari, South Bangalore", micro:"Promont Hill, Banashankari, near Basavanagudi / Kanakapura Road",
  developer:"Tata Housing", type:"apartment", status:"ready", facing:"West", verified:true,
  entry:"2.14", range:"₹2.14 – 7.32 Cr", sqft:"2,376–3,205", priceRange:"₹2.14 – 7.32 Cr", sizeRange:"2,376 – 3,205 sq ft",
  possession:"Ready to move", img:"1600607687939-ce8a6c25118c", lat:12.915, lng:77.546,
  hi:["Hilltop address with panoramic city views","An infinity pool and elevated skywalk"],
  tags:["Hilltop","Infinity Pool","Skywalk"],
  configs:["3 BHK Apartment","4 BHK Apartment","4 BHK Penthouse"],
  overview:"Tata Promont is a landmark hilltop address by Tata Housing, rising over roughly 14 acres atop Promont Hill in Banashankari, south Bangalore. With around 312 residences across four towers, it offers expansive 3 and 4 BHK apartments and penthouses from about 2,376 to 3,205 sq ft, much of the estate given over to greenery. Its commanding elevation grants sweeping views across the city, with the towers visible from the NICE Ring Road, Mysore Road and Jayanagar. Residents enjoy a resort of amenities: an infinity pool, a dramatic skywalk, yoga and meditation decks, party lawn, barbecue pits, indoor and outdoor gyms and a reflexology path. Anchored in established south Bangalore yet close to NICE Road and Kanakapura Road, it blends serene, elevated living with heritage charm.",
  amenities:["Infinity swimming pool","Elevated skywalk","Yoga & meditation deck","Party lawn","Barbecue pits","Indoor & outdoor gym","Hammock zone","Reflexology path","Landscaped gardens"],
  connectivity:[{place:"Banashankari / Basavanagudi",minutes:"5–10 min"},{place:"Kanakapura Road",minutes:"~10 min"},{place:"NICE Ring Road",minutes:"10–15 min"},{place:"Jayanagar",minutes:"~15 min"}],
  usp:["Dramatic hilltop setting with panoramic city views","Resort amenities incl. infinity pool & elevated skywalk","Tata build quality in heritage-rich south Bangalore"],
  sources:["https://www.tatahousing.com/residential-property-in-bangalore/tata-the-promont"]
},
{
  slug:"prestige-kingfisher-towers", name:"Prestige Kingfisher Towers", full:"Prestige Kingfisher Towers",
  loc:"UB City, Central Bangalore", micro:"Vittal Mallya Road, Shanthala Nagar, beside UB City",
  developer:"Prestige Group", type:"penthouse", status:"sold", facing:"North", verified:true,
  entry:"30", range:"₹30 – 35 Cr", sqft:"8,321", priceRange:"₹30 – 35 Cr (full-floor)", sizeRange:"8,321 sq ft per apartment",
  possession:"Ready · completed 2018", img:"1542314831-068cd1dbfeeb", lat:12.971, lng:77.596,
  hi:["One full-floor home per level","A 40,000 sq ft White House-style sky mansion"],
  tags:["Full-floor","Private Lift Lobby","Landmark"],
  configs:["4 BHK Full-floor Apartment · 8,321 sq ft","Sky Mansion Penthouse · ~40,000 sq ft"],
  overview:"Prestige Kingfisher Towers is among Bangalore's most exclusive addresses — a collaboration between the Prestige Group and the UB Group on a roughly 4.5-acre site on Vittal Mallya Road, beside UB City in the heart of the central business district. Comprising three towers of 34 floors, it offers just 81 ultra-luxury residences, with every floor occupied by a single full-floor 4 BHK apartment of about 8,321 sq ft served by a private lift lobby. Completed in 2018 and reaching roughly 122 metres, it ranks among the city's tallest residential structures. Its most storied feature is a 40,000 sq ft sky mansion penthouse, conceived to resemble the White House, complete with helipad, infinity pool, private elevators and rooftop gardens. Kingfisher Towers epitomises rarefied, address-defining luxury in central Bangalore.",
  amenities:["Private lift lobby per apartment","Infinity swimming pool","Helipad (sky mansion)","Rooftop gardens","Clubhouse","Gymnasium","Spa","Concierge & valet","24/7 controlled access"],
  connectivity:[{place:"UB City",minutes:"1–2 min"},{place:"MG Road",minutes:"~5 min"},{place:"Cubbon Park / Kasturba Road",minutes:"~5 min"},{place:"Kempegowda International Airport",minutes:"45–60 min"}],
  usp:["One full-floor 8,321 sq ft apartment per floor with private lobby","Iconic 40,000 sq ft White House-style sky mansion","Prestige–UB landmark among Bangalore's tallest towers"],
  sources:["https://en.wikipedia.org/wiki/Prestige_Kingfisher_Towers"]
},
{
  slug:"phoenix-kessaku", name:"Phoenix Kessaku", full:"Phoenix Kessaku",
  loc:"Rajajinagar, West Bangalore", micro:"Dr. Rajkumar Road, Rajajinagar, opposite Orion Mall / Brigade Gateway",
  developer:"Phoenix Group", type:"penthouse", status:"invite", facing:"East", verified:true,
  entry:"10.9", range:"₹10.9 – 17 Cr", sqft:"4,500–8,000", priceRange:"₹10.9 – 17 Cr", sizeRange:"4,500 – 8,000+ sq ft",
  possession:"Ready to move", img:"1600566753086-00f18fb6b3ea", lat:13.003, lng:77.552,
  hi:["Only one sky bungalow per floor","A 50,000 sq ft Callison-designed clubhouse"],
  tags:["Sky Bungalow","360° Views","Concierge"],
  configs:["4 BHK Sky Bungalow","5 BHK","Penthouse · up to 8,000+ sq ft"],
  overview:"Phoenix Kessaku is among Bangalore's most exclusive ultra-luxury addresses, rising over Rajajinagar opposite Orion Mall as a cluster of soaring towers with just one lavish sky bungalow per floor. Developed by the Phoenix Group, the project comprises around 108 uber-luxury 4 and 5 BHK residences and penthouses spread across 4.5 acres, with structures climbing up to 38 floors. Each home commands sweeping 360-degree views of the cityscape and is wrapped in a 50,000 sq ft Callison-designed clubhouse offering a sky lounge, swimming pool, squash court, mini-theatre, jacuzzi and curated wellness zones. Named after a Japanese philosophy of grace, Kessaku pairs single-residence-per-floor privacy with bespoke interiors and concierge living in upscale West Bangalore.",
  amenities:["50,000 sq ft Callison clubhouse","Swimming pool","Sky lounge","Mini theatre","Squash court","Jacuzzi","Gymnasium","Yoga & aerobics zone","Banquet hall"],
  connectivity:[{place:"Orion Mall / Brigade Gateway",minutes:"Adjacent"},{place:"Sandal Soap Factory Metro",minutes:"~5 min"},{place:"Manipal Hospital",minutes:"~10 min"},{place:"Kempegowda International Airport",minutes:"45–60 min"}],
  usp:["Only one sky bungalow per floor for absolute privacy","Panoramic 360-degree views from towers up to 38 floors","50,000 sq ft world-class Callison clubhouse"],
  sources:["https://www.phoenixkessakurajajinagar.com/"]
},
{
  slug:"phoenix-one-west", name:"Phoenix One West", full:"Phoenix One Bangalore West",
  loc:"Rajajinagar, West Bangalore", micro:"Dr. Rajkumar Road, Rajajinagar, within the Phoenix precinct by Orion Mall",
  developer:"Phoenix Group", type:"apartment", status:"ready", facing:"North-West", verified:true,
  entry:"3.4", range:"₹3.4 – 8 Cr", sqft:"1,890–3,643", priceRange:"₹3.4 – 8 Cr", sizeRange:"1,890 – 3,643 sq ft",
  possession:"Ready to move", img:"1600210492486-724fe5c67fb0", lat:13.006, lng:77.549,
  hi:["A self-contained 17-acre integrated township","Mall, hotel & offices on-site, metro walkable"],
  tags:["Integrated","Garden-facing","Walkable Metro"],
  configs:["2.5 BHK","3 BHK","4 BHK","Penthouse · up to 3,643 sq ft"],
  overview:"Phoenix One Bangalore West is a landmark 17-acre luxury township in Rajajinagar, set within the integrated Phoenix mixed-use precinct alongside Orion Mall, a Sheraton hotel and Grade-A offices. Developed by the Phoenix Group, the gated community comprises seven towers rising up to 30 floors and offering 2.5, 3 and 4 BHK residences and penthouses ranging from roughly 1,890 to 3,643 sq ft. Homes feature wide decks, cross-ventilated layouts, garden- and pool-facing orientations and panoramic city views. Residents enjoy expansive landscaped greens, water features and a full-service clubhouse. The standout draw is its location: a self-contained urban island where premium retail, dining, hospitality and workplaces sit at the doorstep, with a metro station within walking distance.",
  amenities:["Clubhouse (indoor & outdoor)","Swimming pool","Gymnasium","Landscaped gardens & water features","Indoor games","Jogging tracks","Multipurpose hall","Wide private decks","Retail & dining within precinct"],
  connectivity:[{place:"Orion Mall (within precinct)",minutes:"Adjacent"},{place:"Sandal Soap Factory Metro",minutes:"Walkable"},{place:"WTC / Sheraton",minutes:"Within precinct"},{place:"Kempegowda International Airport",minutes:"45–60 min"}],
  usp:["Self-contained 17-acre township with mall, hotel & offices","Seven towers with garden-, pool- and city-facing homes","Walkable metro access in the heart of West Bangalore"],
  sources:["https://phoenixonebangalorewest.org/"]
},
{
  slug:"sobha-international-city", name:"Sobha International City", full:"Sobha International City — Presidential",
  loc:"Off Tumkur Road, NW Bangalore", micro:"Off Tumkur Road, North-West Bengaluru (Bangalore listing unverified — see note)",
  developer:"Sobha Ltd", type:"villa", status:"invite", facing:"North", verified:false,
  entry:"6", range:"₹6 – 14 Cr", sqft:"3,150–7,330", priceRange:"₹6 – 14 Cr (estimated)", sizeRange:"3,150 – 7,330 sq ft (estimated)",
  possession:"Estimated · phased handover", img:"", lat:13.020, lng:77.500,
  hi:["Presidential villa estate living","Sobha's backward-integrated build quality"],
  tags:["Presidential","Low Density","Estimated"],
  configs:["4 BHK Villa","5 BHK Villa","Presidential Villa","Luxury Row House"],
  overview:"Note: the verified 'Sobha International City — Presidential Villas' is on Dwarka Expressway, Gurgaon; a Bangalore listing at this location is unconfirmed and the facts below are estimated from Sobha's International City format. Sobha International City — Presidential is envisioned as an exclusive low-density gated villa township by Sobha Ltd, inspired by the developer's acclaimed format of Presidential Villas, Duplex Villas and luxury row houses. The community is conceived around expansive 4 and 5 BHK villas ranging from roughly 3,150 to 7,330 sq ft, set on landscaped plots with private gardens and only a handful of homes per acre. A signature multi-level grand clubhouse anchors the lifestyle, offering a rooftop pool, gymnasium, meditation hall, sports courts and concierge services, with Sobha's hallmark fit-and-finish throughout.",
  amenities:["Multi-level grand clubhouse","Rooftop swimming pool","Gymnasium","Meditation hall","Tennis & badminton courts","Indoor games","Water bodies & gardens","Private villa pools (select)","24/7 gated security"],
  connectivity:[{place:"Tumkur Road / NH-48 (est.)",minutes:"~5 min"},{place:"Peenya tech belt (est.)",minutes:"~15 min"},{place:"Nelamangala (est.)",minutes:"~15 min"},{place:"Kempegowda International Airport (est.)",minutes:"45–60 min"}],
  usp:["Low-density Presidential Villa estate living","Sobha's renowned backward-integrated build quality","Large multi-level clubhouse with resort amenities"],
  sources:["https://www.sobha.com/bengaluru/sobha-lifestyle-legacy/"]
},
{
  slug:"prestige-leela-residences", name:"Prestige Leela Residences", full:"Prestige Leela Residences",
  loc:"Old Airport Road, E. Bangalore", micro:"HAL 3rd Stage, Kodihalli, adjacent to The Leela Palace",
  developer:"Prestige Group", type:"apartment", status:"ready", facing:"East", verified:true,
  entry:"7.5", range:"₹7.5 – 17.2 Cr", sqft:"2,920–6,509", priceRange:"₹7.5 – 17.2 Cr", sizeRange:"2,920 – 6,509 sq ft",
  possession:"Ready · since 2020", img:"1600573472550-8090b5e0745e", lat:12.960, lng:77.648,
  hi:["Adjacent to The Leela Palace hotel","Only 88 boutique residences across 3 towers"],
  tags:["Boutique","Vaastu","Branded"],
  configs:["3 BHK","4 BHK","5 BHK · up to 6,509 sq ft"],
  overview:"Prestige Leela Residences is an ultra-luxury landmark on Old Airport Road, set right beside the iconic Leela Palace hotel in Kodihalli. Developed by the Prestige Group, this boutique address comprises just 88 exclusive residences across three towers on a compact 3-acre estate, offering expansive 3, 4 and 5 BHK homes from roughly 2,920 to 6,509 sq ft. Now ready to move in, the apartments showcase Vaastu-compliant layouts, refined contemporary facades with landscape lighting and generous proportions designed for gracious entertaining. Residents enjoy a curated suite of amenities including a pool, gym, spa, jacuzzi, sauna, mini-theatre, billiards and banquet spaces. Its prized Old Airport Road location places fine dining, premium retail, leading hospitals and the metro within easy reach.",
  amenities:["Swimming pool","Gymnasium","Spa","Jacuzzi, steam & sauna","Mini theatre","Billiards & indoor games","Banquet & party hall","Salon","Landscaped gardens"],
  connectivity:[{place:"The Leela Palace Hotel",minutes:"Adjacent"},{place:"Indiranagar / 100 Ft Road",minutes:"5–10 min"},{place:"MG Road & CBD",minutes:"~15 min"},{place:"Kempegowda International Airport",minutes:"45–60 min"}],
  usp:["Boutique exclusivity — only 88 residences across 3 towers","Prime Old Airport Road address beside The Leela Palace","Spacious 3–5 BHK homes up to 6,509 sq ft"],
  sources:["https://www.homznspace.com/prestige-leela-residences-reviews/"]
},
{
  slug:"embassy-one-four-seasons", name:"Embassy One — Four Seasons", full:"Embassy One — Four Seasons Private Residences",
  loc:"Bellary Road, North Bangalore", micro:"Ganganagar, Bellary Road (NH-44), near Hebbal",
  developer:"Embassy Group", type:"penthouse", status:"invite", facing:"North", verified:true,
  entry:"7.4", range:"₹7.4 – 30 Cr", sqft:"1,992–5,870", priceRange:"₹7.4 – 30 Cr", sizeRange:"1,992 – 5,870 sq ft",
  possession:"Ready · completed 2022", img:"1600585152220-90363fe7e115", lat:13.020, lng:77.591,
  hi:["Bengaluru's first Four Seasons-serviced homes","Interiors by Yabu Pushelberg, 10-ft ceilings"],
  tags:["Four Seasons","Branded","Concierge"],
  configs:["1–3 BHK","4 BHK","5 BHK","Penthouse · up to 5,870 sq ft"],
  overview:"Embassy One — Four Seasons Private Residences is Bengaluru's premier branded-residence address — the city's first homes serviced by Four Seasons hospitality. Developed by the Embassy Group on a 6.5-acre integrated precinct on Bellary Road near Hebbal, it comprises two 28-storey towers of strictly limited residences alongside a Four Seasons Hotel. Homes span 1 to 5 BHK and penthouses, from roughly 1,992 to 5,870 sq ft, with 10-foot ceilings, central air-conditioning and interiors by world-renowned designers Yabu Pushelberg. Residents enjoy hotel-grade living: 24-hour concierge, a temperature-controlled pool, private spa room, yoga and pilates studio, fitness centre, media room, game room and a climate-controlled wine chamber. Positioned on the airport corridor, it sets the benchmark for turnkey, internationally serviced luxury.",
  amenities:["24-hour Four Seasons concierge","Temperature-controlled pool","Private spa treatment room","Yoga & pilates studio","Fitness centre","Media room","Game room with bar","Climate-controlled wine chamber","Private lobby & driver's lounge"],
  connectivity:[{place:"Columbia Asia Hospital",minutes:"5–10 min"},{place:"Vidhana Soudha / CBD",minutes:"~15 min"},{place:"Embassy Manyata Business Park",minutes:"~15 min"},{place:"Kempegowda International Airport",minutes:"40–45 min"}],
  usp:["Bengaluru's first Four Seasons-serviced private residences","Interiors by Yabu Pushelberg with 10-foot ceilings","Integrated 6.5-acre precinct with a Four Seasons hotel"],
  sources:["https://www.luxuryresidences.in/four-seasons-private-residences-bellary-road-bangalore/"]
}
];

/* ============================================================
   Real property photography (hero + gallery), keyed by slug.
   index 0 = hero. Generated from supplied Exclusive Residences
   Images. Falls back to Unsplash img field where absent.        
   ============================================================ */
export const PROP_IMAGES: Record<string, string[]> = {
  "adarsh-palm-retreat": ["images/adarsh-palm-retreat/0.png"],
  "bhartiya-city-leela": ["images/bhartiya-city-leela/0.png","images/bhartiya-city-leela/1.webp","images/bhartiya-city-leela/2.webp","images/bhartiya-city-leela/3.webp","images/bhartiya-city-leela/4.png"],
  "brigade-orchards-signature": ["images/brigade-orchards-signature/0.png"],
  "embassy-boulevard": ["images/embassy-boulevard/0.png"],
  "embassy-grove": ["images/embassy-grove/0.png"],
  "embassy-lake-terraces": ["images/embassy-lake-terraces/0.png"],
  "embassy-one-four-seasons": ["images/embassy-one-four-seasons/0.png","images/embassy-one-four-seasons/1.png","images/embassy-one-four-seasons/2.png","images/embassy-one-four-seasons/3.png","images/embassy-one-four-seasons/4.png"],
  "embassy-springs-the-grove": ["images/embassy-springs-the-grove/0.png"],
  "godrej-reserve": ["images/godrej-reserve/0.png","images/godrej-reserve/1.webp","images/godrej-reserve/2.webp","images/godrej-reserve/3.webp","images/godrej-reserve/4.webp"],
  "nambiar-bellesa": ["images/nambiar-bellesa/0.png","images/nambiar-bellesa/1.png","images/nambiar-bellesa/2.png","images/nambiar-bellesa/3.webp"],
  "phoenix-kessaku": ["images/phoenix-kessaku/0.png"],
  "phoenix-one-west": ["images/phoenix-one-west/0.png","images/phoenix-one-west/1.png","images/phoenix-one-west/2.png","images/phoenix-one-west/3.png","images/phoenix-one-west/4.png"],
  "prestige-dew-drops": ["images/prestige-dew-drops/0.png","images/prestige-dew-drops/1.png","images/prestige-dew-drops/2.png","images/prestige-dew-drops/3.png"],
  "prestige-golfshire": ["images/prestige-golfshire/0.webp","images/prestige-golfshire/1.webp","images/prestige-golfshire/2.webp","images/prestige-golfshire/3.webp"],
  "prestige-kingfisher-towers": ["images/prestige-kingfisher-towers/0.png","images/prestige-kingfisher-towers/1.webp","images/prestige-kingfisher-towers/2.webp","images/prestige-kingfisher-towers/3.webp"],
  "prestige-leela-residences": ["images/prestige-leela-residences/0.png","images/prestige-leela-residences/1.png","images/prestige-leela-residences/2.png","images/prestige-leela-residences/3.png","images/prestige-leela-residences/4.png"],
  "prestige-white-meadows": ["images/prestige-white-meadows/0.png"],
  "sobha-international-city": ["images/sobha-international-city/0.png","images/sobha-international-city/1.webp","images/sobha-international-city/2.webp","images/sobha-international-city/3.webp","images/sobha-international-city/4.webp","images/sobha-international-city/5.webp"],
  "tata-promont": ["images/tata-promont/0.png","images/tata-promont/1.png","images/tata-promont/2.png","images/tata-promont/3.png","images/tata-promont/4.jpg"],
  "total-environment-rhapsody": ["images/total-environment-rhapsody/0.png"],
};

export type Property = (typeof PROPERTIES)[number];
